module.exports = [
  { teamName: 'Celtics', location: 'Boston' },
  { teamName: 'Nets', location: 'Brooklyn' },
  { teamName: 'Knicks', location: 'New York' },
  { teamName: '76ers', location: 'Philadelphia' },
  { teamName: 'Raptors', location: 'Toronto' },
  { teamName: 'Warriors', location: 'Golden State' },
  { teamName: 'Clippers', location: 'Los Angeles' },
  { teamName: 'Lakers', location: 'Los Angeles' },
  { teamName: 'Suns', location: 'Phoenix' },
  { teamName: 'Kings', location: 'Sacramento' },
  { teamName: 'Bulls', location: 'Chicago' },
  { teamName: 'Cavaliers', location: 'Cleveland' },
  { teamName: 'Pistons', location: 'Detroit' },
  { teamName: 'Pacers', location: 'Indiana' },
  { teamName: 'Bucks', location: 'Milwaukee' },
  { teamName: 'Mavericks', location: 'Dallas' },
  { teamName: 'Rockets', location: 'Houston' },
  { teamName: 'Grizzlies', location: 'Memphis' },
  { teamName: 'Pelicans', location: 'New Orleans' },
  { teamName: 'Spurs', location: 'San Antonio' },
  { teamName: 'Hawks', location: 'Atlanta' },
  { teamName: 'Hornets', location: 'Charlotte' },
  { teamName: 'Heat', location: 'Miami' },
  { teamName: 'Magic', location: 'Orlando' },
  { teamName: 'Wizards', location: 'Washington' },
  { teamName: 'Nuggets', location: 'Denver' },
  { teamName: 'Timberwolves', location: 'Minnesota' },
  { teamName: 'Thunder', location: 'Oklahoma City' },
  { teamName: 'Trail Blazers', location: 'Portland' },
  { teamName: 'Jazz', location: 'Utah' }
];
